{{- if .Values.rbac.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    app: sre-dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.k8sRemediator.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-remediator-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-remediator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-remediator-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.k8sRemediator.serviceAccount.name }}
    namespace: {{ .Values.global.namespace }}
{{- end }}
